name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  # Job 1: Gera apenas as Estatísticas Gerais
  github-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroHenriqueOficial
          template: classic
          base: header, community, repositories, metadata
          config_theme: radical
          config_timezone: America/Sao_Paulo

  # Job 2: Gera apenas as Linguagens (Com suas personalizações)
  github-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroHenriqueOficial
          template: classic
          base: "" # Remove o cabeçalho e o "5 Languages"
          config_theme: radical # Aplica o tema Rosa/Azul da Foto 2
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_title: "Most Used Languages" # Título com Iniciais Maiúsculas
          config_timezone: America/Sao_Paulo
