name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente
permissions:
  contents: write

jobs:
  github-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroHenriqueOficial
          template: classic
          base: "" # Remove o cabeçalho e estatísticas gerais
          config_theme: radical
          config_timezone: America/Sao_Paulo
          
          # Configurações de Linguagens
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_title: "Most Used Languages"
