name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza todo dia à meia-noite
  workflow_dispatch: # Permite que você rode manualmente para testar
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroHenriqueOficial # <--- Verifique se este é seu usuário exato
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin de Linguagens (Visual e Colorido)
          plugin_languages: yes
          plugin_languages_ignored: html, css # Ignora linguagens simples se quiser
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
